	sadot = {
		label = 'SADOT',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 150 },
			['1'] = { name = 'B&I Division', payment = 200 },
			['2'] = { name = 'TMD', payment = 250 },
			['3'] = { name = 'HMD', payment = 300 },
			['4'] = { name = 'Utility Specialists', payment = 350 },
			['5'] = { name = 'Traffic Engineer', payment = 400 },
			['6'] = { name = 'Senior Traffic Engineer', payment = 450 },
			['7'] = { name = 'Field Tech', payment = 500 },
			['8'] = { name = 'Sr. Field Tech', payment = 550 },
			['9'] = { name = 'Saftey Officer', payment = 600 },
			['10'] = { name = 'Field Supervisor', payment = 600 },
			['11'] = { name = 'Senior Field Supervisor', payment = 600 },
			['12'] = { name = 'Asst. Director of Trans', isboss = true, payment = 600 },
			['13'] = { name = 'Dept. Director of Trans', isboss = true, payment = 600 },
			['14'] = { name = 'Director of Trans', isboss = true, payment = 600 },
		},
	},